import {readdirSync, statSync, readFileSync} from 'fs';
import {join} from 'path';

import { parse } from 'csv-parse/sync';

export default function importTransactions(directory) {
    const dirContent = readdirSync(directory);
    const transactions = [];

    for (const dirEntry of dirContent) {
        const filename = join(directory, dirEntry);
        const stats = statSync(filename);

        if (stats.isDirectory()) {
            transactions.push(...importTransactions(filename));
        } else if (
            dirEntry.endsWith('.csv')
            && (!dirEntry.startsWith('SUMMARY') // removes "summary" files (generated by crypto.com/exchange exports)
                && !dirEntry.startsWith('REQUEST')) // removes "request" files (generated by crypto.com/exchange exports)
        ) {
            transactions.push(...parse(readFileSync(filename)));
        }
    }

    return transactions;
}